---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Викидайли
description: В цьому проекті ви дізнаєтеся, як створити гру-платформер, в якій потрібно буде дістатися кінця рівня ухиляючись від рухомих куль.
version: 3
last_tested: 2018-10-10
steps:
  - 
    title: З днем народження
  - 
    title: Рухи персонажа
  - 
    title: "Challenge: completing the level"
    challenge: true
  - 
    title: Гравітація і стрибки
  - 
    title: 'Challenge: improved jumping'
    challenge: true
  - 
    title: Відбивати м'ячі
  - 
    title: 'Challenge: random balls'
    challenge: true
  - 
    title: Лазери!
  - 
    title: 'Challenge: більше перешкод'
    challenge: true
  - 
    title: 'Challenge: improved gravity'
    challenge: true
  - 
    title: 'Challenge: more lives'
    challenge: true
  - 
    title: Що далі?
