---
hero_image: images/banner.png
theme: жовтий
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Викидайли
description: В цьому проекті ви дізнаєтеся, як створити гру-платформер, в якій потрібно буде дістатися кінця рівня ухиляючись від рухомих куль.
original_url: https://codeclubprojects.org/en-GB/scratch/dodgeball
interests: ігри
technologies: scratch
site_areas: проекти
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Викидайли
  - 
    title: Рухи персонажа
  - 
    title: 'Завдання: Пройти рівень'
  - 
    title: Гравітація і стрибки
  - 
    title: 'Завдання: Покращений стрибок'
  - 
    title: Відбивати м'ячі
  - 
    title: 'Завдання: Випадові м''ячі'
  - 
    title: Лазери!
  - 
    title: 'Завдання: більше перешкод'
  - 
    title: 'Завдання: Покращена гравітація'
  - 
    title: 'Завдання: Більше життів'
