---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Trefbal
description: Maak een platformspel, waarin je de bewegende ballen moet ontwijken en
  het level moet halen
version: 4.0.0
last_tested: 2018-10-10
steps:
- title: Inleiding
- title: Voortbeweging personage
- title: 'Uitdaging: het level halen'
  challenge: true
- title: Zwaartekracht en springen
  completion:
  - engaged
- title: 'Uitdaging: beter springen'
  challenge: true
- title: Trefballen
- title: 'Uitdaging: willekeurige ballen'
  challenge: true
- title: Lasers!
  completion:
  - internal
- title: 'Uitdaging: meer obstakels'
  challenge: true
- title: 'Uitdaging: verbeterde zwaartekracht'
  challenge: true
- title: 'Uitdaging: meer levens'
  challenge: true
- title: Wat nu?
