---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Trefbal
description: Maak een platformspel, waarin je de bewegende ballen moet ontwijken en het level moet halen.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Voortbeweging personage
  - 
    title: "Uitdaging: het level halen"
    challenge: true
  - 
    title: Zwaartekracht en springen
  - 
    title: 'Uitdaging: beter springen'
    challenge: true
  - 
    title: Trefballen
  - 
    title: 'Uitdaging: willekeurige ballen'
    challenge: true
  - 
    title: Lasers!
  - 
    title: 'Uitdaging: meer hindernissen'
    challenge: true
  - 
    title: 'Uitdaging: verbeterde zwaartekracht'
    challenge: true
  - 
    title: 'Uitdaging: meer levens'
    challenge: true
  - 
    title: What next?
