hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Dodgeball
description: Create a platform game, in which you have to dodge the moving balls and reach the end of the level.
original_url: https://codeclubprojects.org/en-GB/scratch/dodgeball
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Character movement
- title: "Challenge: Completing the level"
  challenge: true
- title: Gravity and jumping
- title: 'Challenge: Improved jumping'
  challenge: true
- title: Dodging balls
- title: 'Challenge: Random balls'
  challenge: true
- title: Lasers!
- title: 'Challenge: More obstacles'
  challenge: true
- title: 'Challenge: Improved gravity'
  challenge: true
- title: 'Challenge: More lives'
  challenge: true
