hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Boldundvigelsesspil
description: Lav et platformspil hvor du undviger rullende bolde, og hvor du skal nå slutzonen.
version: 4.0.0
last_tested: 2018-10-10
steps:
- title: Introduktion
- title: Figur Bevægelse
- title: "Udfordring: afslutning af niveauet"
  challenge: true
- title: Tyngdekraft og at hoppe
- title: 'Udfordring: bedre hop'
  challenge: true
- title: Dodging balls
- title: 'Udfordring: tilfældige bolde'
  challenge: true
- title: Lasere!
- title: 'Udfordring: flere forhindringer'
  challenge: true
- title: 'Udfordring: forbedret tyngdekraft'
  challenge: true
- title: 'Udfordring: flere liv'
  challenge: true
- title: Hvad er det næste?
