---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Preskakanje lopti
description: U ovom projektu ćeš naučiti napraviti igru u kojoj igrač treba izbjegavati lopte koje se kreću i stići do kraja nivoa.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Preskakanje lopti
  - 
    title: Character movement
  - 
    title: "Challenge: completing the level"
    challenge: true
  - 
    title: Gravity and jumping
  - 
    title: 'Challenge: improved jumping'
    challenge: true
  - 
    title: Dodging balls
  - 
    title: 'Challenge: random balls'
    challenge: true
  - 
    title: Lasers!
  - 
    title: 'Challenge: more obstacles'
    challenge: true
  - 
    title: 'Challenge: improved gravity'
    challenge: true
  - 
    title: 'Challenge: more lives'
    challenge: true
  - 
    title: What next?
