---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Esquiva-pelotas
description: Crea un juego de plataformas en el que tengas que esquivar pelotas y llegar al final del nivel
version: 4.0.0
last_tested: 2018-10-10
steps:
  - 
    title: Introducción
  - 
    title: Movimientos del personaje
  - 
    title: "Desafío: Acabar el nivel"
    challenge: true
  - 
    title: Gravedad y saltos
  - 
    title: 'Desafío: Mejores saltos'
    challenge: true
  - 
    title: Esquivando las pelotas
  - 
    title: 'Desafío: Pelotas aleatorias'
    challenge: true
  - 
    title: '¡Láseres!'
  - 
    title: 'Desafío: Más obstáculos'
    challenge: true
  - 
    title: 'Desafío: Mejorando la gravedad'
    challenge: true
  - 
    title: 'Desafío: Más vidas'
    challenge: true
  - 
    title: Y ahora ¿qué?
