---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Alón Prisionero
description: Crea un juego de plataforma en el que tengas que esquivar pelotas y llegar al final del nivel.
original_url: https://codeclubprojects.org/en-GB/scratch/dodgeball
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introducción
- title: Movimientos del personaje
- title: 'Reto: Acabar el nivel'
- title: Gravedad y saltos
- title: 'Reto: Salto mejorado'
- title: Esquivar los balones
- title: 'Reto: Balones aleatorios'
- title: ¡Láseres!
- title: 'Reto: Más obstáculos'
- title: 'Reto: Gravedad mejorada'
- title: 'Reto: Más vidas'

