---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Alón Prisionero
description: Crea un juego de plataforma en el que tengas que esquivar pelotas y llegar al final del nivel.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Movimientos del personaje
  - 
    title: "Reto: Acabar el nivel"
    challenge: true
  - 
    title: Gravedad y saltos
  - 
    title: 'Reto: Salto mejorado'
    challenge: true
  - 
    title: Esquivar los balones
  - 
    title: 'Reto: Balones aleatorios'
    challenge: true
  - 
    title: '¡Láseres!'
  - 
    title: 'Reto: Más obstáculos'
    challenge: true
  - 
    title: 'Reto: Gravedad mejorada'
    challenge: true
  - 
    title: 'Reto: Más vidas'
    challenge: true
  - 
    title: What next?
