---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Osgoi'r bêl
description: Creu gêm blatfform lle rydych chi'n osgoi peli sy'n symud i gyrraedd
  diwedd y lefel
version: 4.0.0
last_tested: 2018-10-10
steps:
- title: Cyflwyniad
- title: Symudiad y cymeriad
- title: 'Her: cwblhau''r lefel'
  challenge: true
- title: Disgyrchiant a neidio
  completion:
  - engaged
- title: 'Her: gwella''r neidio'
  challenge: true
- title: Osgoi peli
- title: 'Her: peli ar hap'
  challenge: true
- title: Laser!
  completion:
  - internal
- title: 'Her: mwy o rwystrau'
  challenge: true
- title: 'Her: gwell disgyrchiant'
  challenge: true
- title: 'Her: mwy o fywydau'
  challenge: true