---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Völkerball
description: In diesem Projekt lernst Du, wie Du ein Plattform-Spiel erstellst, in dem Du sich bewegenden Bällen ausweichen und das Ende des Levels erreichen musst.
version: 3
last_tested: 2018-10-10
steps:
  - 
    title: Einleitung
  - 
    title: Bewegung der Spielfigur
  - 
    title: "Herausforderung: Das Level abschließen"
    challenge: true
  - 
    title: Schwerkraft und springen
  - 
    title: 'Herausforderung: Verbessertes Springen'
    challenge: true
  - 
    title: Bälle ausweichen
  - 
    title: 'Herausforderung: zufällige Bälle'
    challenge: true
  - 
    title: Laser!
  - 
    title: 'Herausforderung: Mehr Hindernisse'
    challenge: true
  - 
    title: 'Herausforderung: Verbesserte Schwerkraft'
    challenge: true
  - 
    title: 'Herausforderung: Mehr Leben'
    challenge: true
  - 
    title: Wie geht es weiter?
