---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Treffball
description: In diesem Projekt lernst Du, wie Du ein Plattform-Spiel erstellst, in dem Du sich bewegenden Bällen ausweichen und das Ende des Levels erreichen musst.
original_url: https://codeclubprojects.org/en-GB/scratch/dodgeball
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Einführung
- title: Bewegung der Spielfigur
- title: 'Herausforderung: Das Level abschließen'
- title: Schwerkraft und springen
- title: 'Herausforderung: Vernessertes Springen'
- title: Springende Bälle
- title: 'Herqusforderung: Willkürliche Bälle'
- title: Laser!
- title: 'Herausforderung: Mehr Hindernisse'
- title: 'Herausforderung: Verbesserte Schwerkraft'
- title: 'Herausforderung: Mehr Leben'

