---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Rațele și vânătorii
description: În acest proiect vei învăța cum să creezi un joc în care va trebui să te ferești de mingile care se mișcă pentru a ajunge la sfârșitul nivelului.
version: 3
last_tested: 2018-10-10
steps:
  - 
    title: Introducere
  - 
    title: Mișcarea personajului
  - 
    title: "Provocare: completarea nivelului"
    challenge: true
  - 
    title: Gravitație și sărituri
  - 
    title: 'Provocare: sărituri îmbunătățite'
    challenge: true
  - 
    title: Evitarea mingilor
  - 
    title: 'Provocare: mingi diferite'
    challenge: true
  - 
    title: Lasere!
  - 
    title: 'Provocare: mai multe obstacole'
    challenge: true
  - 
    title: 'Provocare: îmbunătățirea gravitației'
    challenge: true
  - 
    title: 'Provocare: mai multe vieți'
    challenge: true
  - 
    title: Ce urmează?
