---
hero_image: images/banner.png
theme: galben
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Ratele  si vanatorii
description: În acest proiect vei învăța cum să creezi o platformă pentru un joc în care va trebui să te ferești de mingile care se mișcă și să ajungi la sfârșitul nivelului.
original_url: http://projects.codeclubworld.org/ro-RO/02_scratch-2/02/Dodgeball.html
interests: jocuri
technologies: scratch
site_areas: proiecte
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Dodgeball
  - 
    title: Cinematica personajului
  - 
    title: 'Scop: Finalizarea nivelului'
  - 
    title: Gravitate si sarituri
  - 
    title: 'Provocare: Imbunatatirea sariturilor'
  - 
    title: Evita mingea
  - 
    title: 'Provocare: Mingi aleatorii'
  - 
    title: Laser!
  - 
    title: 'Provocare: Mai multe obstacole'
  - 
    title: 'Provocare: Imbunatatirea controlului gravitatii'
  - 
    title: 'Provocare: Mai multe vieti'
