---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Ratele  si vanatorii
description: În acest proiect vei învăța cum să creezi o platformă pentru un joc în care va trebui să te ferești de mingile care se mișcă și să ajungi la sfârșitul nivelului.
version: 3
last_tested: 2018-10-10
steps:
  - 
    title: Dodgeball
  - 
    title: Cinematica personajului
  - 
    title: "Provocare: completarea nivelului"
    challenge: true
  - 
    title: Gravitatie si sarituri
  - 
    title: 'Provocare: sărituri îmbunătățite'
    challenge: true
  - 
    title: Evita mingea
  - 
    title: 'Provocare: bile aleatoare'
    challenge: true
  - 
    title: Lasere!
  - 
    title: 'Provocarea: Mai multe obstacole'
    challenge: true
  - 
    title: 'Provocare: îmbunătățirea gravitației'
    challenge: true
  - 
    title: 'Provocare: mai multe vieți'
    challenge: true
  - 
    title: Ce urmează?
