---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Ratele  si vanatorii
description: În acest proiect vei învăța cum să creezi o platformă pentru un joc în care va trebui să te ferești de mingile care se mișcă și să ajungi la sfârșitul nivelului.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Dodgeball
  - 
    title: Cinematica personajului
  - 
    title: "Challenge: completing the level"
    challenge: true
  - 
    title: Gravitate si sarituri
  - 
    title: 'Challenge: improved jumping'
    challenge: true
  - 
    title: Evita mingea
  - 
    title: 'Challenge: random balls'
    challenge: true
  - 
    title: Laser!
  - 
    title: 'Challenge: more obstacles'
    challenge: true
  - 
    title: 'Challenge: improved gravity'
    challenge: true
  - 
    title: 'Challenge: more lives'
    challenge: true
  - 
    title: What next?
