---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: EsquivaBol
description: Neste projeto você vai aprender como fazer um jogo de plataforma, em que você tem que se esquivar das bolas em movimento e chegar ao final do nível.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: EsquivaBol
  - 
    title: Character movement
  - 
    title: "Challenge: completing the level"
    challenge: true
  - 
    title: Gravity and jumping
  - 
    title: 'Challenge: improved jumping'
    challenge: true
  - 
    title: Dodging balls
  - 
    title: 'Challenge: random balls'
    challenge: true
  - 
    title: Lasers!
  - 
    title: 'Challenge: more obstacles'
    challenge: true
  - 
    title: 'Challenge: improved gravity'
    challenge: true
  - 
    title: 'Challenge: more lives'
    challenge: true
  - 
    title: What next?
