---
hero_image: imagens/banner.png
listed: true
ingredient: false
copyedit: false
title: EsquivaBol
description: Neste projeto você vai aprender como fazer um jogo de plataforma, em que você tem que se esquivar das bolas em movimento e chegar ao final do nível.
version: 3
last_tested: 2018-10-10
steps:
  - 
    title: Introdução
  - 
    title: Movimento do personagem
  - 
    title: "Desafio: completar o nível"
    challenge: true
  - 
    title: Gravidade e Salto
  - 
    title: 'Desafio: salto melhorado'
    challenge: true
  - 
    title: Esquivando das bolas
  - 
    title: 'Desafio: bolas aleatórias'
    challenge: true
  - 
    title: Lasers!
  - 
    title: 'Desafio: mais obstáculos'
    challenge: true
  - 
    title: 'Desafio: Gravidade melhorada'
    challenge: true
  - 
    title: 'Desafio: mais vidas'
    challenge: true
  - 
    title: O que vem depois?
