---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Pazi, žoga!
description: Ustvari ploščadno igro, v kateri se moraš izmikati žogam in priti do konca stopnje
version: 4.0.0
last_tested: 2018-10-10
steps:
  - 
    title: Uvod
  - 
    title: Gibanje likov
  - 
    title: "Izziv: Dokončana stopnja"
    challenge: true
  - 
    title: Gravitacija in skoki
  - 
    title: 'Izziv: izboljšani skoki'
    challenge: true
  - 
    title: Izmikanje žogam
  - 
    title: 'Izziv: naključne žoge'
    challenge: true
  - 
    title: Laserji!
  - 
    title: 'Izziv: več ovir'
    challenge: true
  - 
    title: 'Izziv: izboljšana gravitacija'
    challenge: true
  - 
    title: 'Izziv: več življenj'
    challenge: true
  - 
    title: Kaj sledi?
