---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: تفادي الكرات
description: Create a platform game in which you dodge moving balls to reach the end of the level
version: 4.0.0
last_tested: 2018-10-10
steps:
  - 
    title: المقدمة
  - 
    title: حركة الشخصية
  - 
    title: "Challenge: completing the level"
    challenge: true
  - 
    title: الجاذبية و القفز
  - 
    title: 'Challenge: improved jumping'
    challenge: true
  - 
    title: تفادي الكرات
  - 
    title: 'Challenge: random balls'
    challenge: true
  - 
    title: أشعة الليزر!
  - 
    title: 'Challenge: more obstacles'
    challenge: true
  - 
    title: 'Challenge: improved gravity'
    challenge: true
  - 
    title: 'Challenge: more lives'
    challenge: true
  - 
    title: ماذا بعد؟
