---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: تفادي الكرات
description: قم بإنشاء برنامج لعبة تتجنب فيها الكرات المتحركة للوصول إلى نهاية المستوى
version: 4.0.0
last_tested: 2018-10-10
steps:
  - title: المقدمة
  - title: حركة الشخصية
  - title: "التحدي: إكمال المستوى"
    challenge: true
  - title: الجاذبية و القفز
  - title: 'التحدي: تحسين القفز'
    challenge: true
  - title: تفادي الكرات
  - title: 'التحدي: كرات عشوائية'
    challenge: true
  - title: أشعة الليزر!
  - title: 'التحدي: المزيد من العقبات (او العوائق)'
    challenge: true
  - title: 'التحدي: تحسين الجاذبية'
    challenge: true
  - title: 'التحدي: محاولات أخرى'
    challenge: true
  - title: ماذا بعد؟
