---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Dwa ognie
description: Naucz się, jak stworzyć grę platformową, w której gracz musi unikać toczących się piłek.
version: 3
last_tested: 2018-10-10
steps:
  - 
    title: Wprowadzenie
  - 
    title: Sterowanie postacią
  - 
    title: "Wyzwanie: ukończenie poziomu"
    challenge: true
  - 
    title: Grawitacja i skakanie
  - 
    title: 'Wyzwanie: poprawione skakanie'
    challenge: true
  - 
    title: Unikanie piłek
  - 
    title: 'Wyzwanie: losowe piłki'
    challenge: true
  - 
    title: Lasery!
  - 
    title: 'Wyzwanie: więcej przeszkód'
    challenge: true
  - 
    title: 'Wyzwanie: poprawiona grawitacja'
    challenge: true
  - 
    title: 'Wyzwanie: więcej żyć'
    challenge: true
  - 
    title: Co następne?
