---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Dwa ognie
description: Naucz się, jak stworzyć grę platformową, w której gracz musi unikać toczących się piłek.
version: 3
last_tested: 2018-10-10
steps:
  - 
    title: Wprowadzenie
  - 
    title: Sterowanie postacią
  - 
    title: "Challenge: completing the level"
    challenge: true
  - 
    title: Grawitacja i skakanie
  - 
    title: 'Challenge: improved jumping'
    challenge: true
  - 
    title: Unikanie piłek
  - 
    title: 'Challenge: random balls'
    challenge: true
  - 
    title: Lasery!
  - 
    title: 'Wyzwanie: więcej przeszkód'
    challenge: true
  - 
    title: 'Challenge: improved gravity'
    challenge: true
  - 
    title: 'Challenge: more lives'
    challenge: true
  - 
    title: Co następne?
