---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Dwa ognie
description: W tym projekcie nauczysz się jak stworzyć grę platformową, w której będziesz musiał zbić poruszające się piłki i ukończyć poziom.
original_url: https://codeclubprojects.org/en-GB/scratch/dodgeball
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Wstęp
  - 
    title: Poruszanie się postacią
  - 
    title: 'Wyzwanie: Ukończenie poziomu'
  - 
    title: Grawitacja i skakanie
  - 
    title: 'Wyzwanie: Ulepszone skakanie'
  - 
    title: Unikanie piłek
  - 
    title: 'Wyzwanie: Różne piłki'
  - 
    title: Lasery!
  - 
    title: 'Wyzwanie: Więcej przeszkód'
  - 
    title: 'Wyzwanie: Ulepszona grawitacja'
  - 
    title: 'Wyzwanie: Więcej żyć'
