---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Između dvije vatre
description: Kreiraj platformsku igru u kojoj treba da izbjegavaš lopte koje se kreću i dođeš do kraja nivoa.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Kretanje karaktera
  - 
    title: "Izazov: Dovršavanje nivoa"
    challenge: true
  - 
    title: Gravitacija i skokovi
  - 
    title: 'Izazov: Poboljšan skok'
    challenge: true
  - 
    title: Izbjegavanje lopti
  - 
    title: 'Izazov: Slučajne lopte'
    challenge: true
  - 
    title: Laseri!
  - 
    title: 'Izazov: Više prepreka'
    challenge: true
  - 
    title: 'Izazov: Poboljšana gravitacija'
    challenge: true
  - 
    title: 'Izazov: Više života'
    challenge: true
  - 
    title: What next?
