---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Ballon chasseur
description: Apprends à programmer ton propre jeu de plateforme!
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Mouvement du personnage
  - 
    title: "Défi : Achèvement du niveau"
    challenge: true
  - 
    title: Gravité et saut
  - 
    title: 'Défi : Bond Amélioré'
    challenge: true
  - 
    title: Esquive des balles
  - 
    title: 'Défi : balles aléatoires'
    challenge: true
  - 
    title: Lasers!
  - 
    title: 'Défi : Plus d''obstacles'
    challenge: true
  - 
    title: 'Défi : gravité améliorée'
    challenge: true
  - 
    title: 'Défi : Plus de vies'
    challenge: true
  - 
    title: What next?
