---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Ballon chasseur
description: Apprends à programmer ton propre jeu de plateforme!
original_url: https://codeclubprojects.org/en-GB/scratch/dodgeball
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: Mouvement du personnage
- title: 'Défi : Achèvement du niveau'
- title: Gravité et saut
- title: 'Défi : Bond Amélioré'
- title: Esquive des balles
- title: 'Défi : balles aléatoires'
- title: Lasers!
- title: "Défi : Plus d'obstacles"
- title: 'Défi : gravité améliorée'
- title: 'Défi : Plus de vies'

