---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Dodgeball
description: Crea un gioco a piattaforme in cui dovrai schivare le palle in movimento e raggiungere la fine del livello.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Movimento del personaggio
  - 
    title: "Sfida: Completare il livello"
    challenge: true
  - 
    title: Gravità e salti
  - 
    title: 'Sfida: Salto migliorato'
    challenge: true
  - 
    title: Palle da schivare
  - 
    title: 'Sfida: Palle a caso'
    challenge: true
  - 
    title: Laser!
  - 
    title: 'Sfida: Altri ostacoli'
    challenge: true
  - 
    title: 'Sfida: Salto migliorato'
    challenge: true
  - 
    title: 'Sfida: Altre vite'
    challenge: true
  - 
    title: What next?
