---
hero_image: images / banner.png
listed: true
ingredient: false
copyedit: false
title: ඩොජ්බෝල්(Dodgeball)
description: වේදිකාවක්මත චලනයවන බෝල මතින් පැනයමින්(doge) ක්‍රීඩාවේ ඊළඟ මට්ටම(level) කරා යාහැකි ක්‍රීඩාවක් නිර්මණය කිරීම.
version: 4.0.0
last_tested: 2018-10-10
steps:
  - 
    title: හැදින්වීම
  - 
    title: චරිත(character) චලනය(movement)
  - 
    title: "Challenge: මට්ටම සම්පූර්ණ කිරීම"
    challenge: true
  - 
    title: ගුරුත්වාකර්ෂණය සහ උඩ පැනීම
  - 
    title: 'Challenge: තවත් උඩ පැනීම '
    challenge: true
  - 
    title: බෝල වලින් පනීම(Doge balls)
  - 
    title: 'Challenge:  අහඹු(random) බෝල'
    challenge: true
  - 
    title: ලේසර්(Lasers)!
  - 
    title: 'Challenge:  තවත් බාධක'
    challenge: true
  - 
    title: 'Challenge: වැඩි දියුණු කළ ගුරුත්වාකර්ෂණය'
    challenge: true
  - 
    title: 'Challenge: තවත් ජීවිත'
    challenge: true
  - 
    title: ඊලඟට කුමක්ද?
